Algoritmo ALCANCIA
	DEFINIR CANTIDAD , X, VAL Como Entero
	CANTIDAD=0;
	X=0;
	VAL=0;
	
	PARA X=1 HASTA 4 CON PASO 1 HACER 
		CANTIDAD= CANTIDAD + 1;
		ESCRIBIR " DIGITE EL VALOR DE CADA MONEDA: ";
		LEER VAL;
		TOTAL=TOTAL + VAL;
	FinPara
	
	Escribir " CANTIDAD DE MONEDAS: " , CANTIDAD;
	ESCRIBIR " CANTIDAD DE DINER0 AHORRADO: ", TOTAL;
	
FinAlgoritmo
