Algoritmo EMPEZANDO
	DEFINIR NOMBRE Como Caracter
	DEFINIR EDAD Como Entero
	DEFINIR  APELLIDO,SEXO COMO CARACTER
	
	ESCRIBIR " CUAL ES SU NOMBRE? ";
	LEER NOMBRE;
	
	ESCRIBIR " APELLIDO: ";
	LEER APELLIDO
	
	ESCRIBIR " CUAL ES SU EDAD? ";
	LEER EDAD;
	
	ESCRIBIR " SEXO: ";
	LEER SEXO;
	
	ESCRIBIR "NOMBRE: ", NOMBRE   , " APELLIDO: ", APELLIDO, "  EDAD: ", EDAD , " SEXO: " , SEXO;
	
	
FinAlgoritmo
