Algoritmo MULTIPLICACION_20_NUMEROS
	
	DEFINIR TOTAL, X Como REAL
	TOTAL=1;
	X=0;
	ESCRIBIR " MULTIPLICACION DE 20 PRIMEROS NUMEROS NATURALES "; 
	
	PARA X=1 HASTA 20 CON PASO 1 Hacer
		TOTAL = TOTAL * X;
	FinPara
	
	ESCRIBIR " EL RESULTADO TOTAL ES: " , TOTAL;
	
FinAlgoritmo
